Improved error handling

diff --git a/enshrouded/actions/server_start b/enshrouded/actions/server_start
--- a/enshrouded/actions/server_start
+++ b/enshrouded/actions/server_start
@@ -6,9 +6,7 @@ echo "###### Server Enshrouded.$SERVER_NAME [STARTING]"
 echo $PORT > /home/steam/config/port
 echo $SERVER_NAME > /home/steam/config/server_name 
 echo $PASSWORD > /home/steam/config/password
-#echo "THIS SERVER IS KNOWN TO TAKE UP TO 15 MINUTES TO START." > /home/steam/config/notice
-update_server_settings
-# CUSTOM GAME SERVER COMMAND
 cd $INSTALL_DIR
-
+update_server_settings || { echo " [x] Failed to update server settings."; exit 1; }
+# CUSTOM GAME SERVER COMMAND
 /home/steam/steamcmd/compatibilitytools.d/GE-Proton9-18/proton run enshrouded_server.exe
